### ISSUE TITLE
Various inconsistencies to check

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/deploy#71] opened 2019-11-02 15:38 UTC
Just noting some inconsistencies as I review the files. I'm not sure if these are on purpose, or should be made consistent.

* [ ] `prometheus-client-apache` is last in `top.sls`, except for `ocds-docs-*` and `standard-search`
* [x] `apache_module.enabled` generally has `watch_in: service: apache2`, except in `apache-proxy.sls` and `ocds-docs-common.sls`.
* [ ] `require` is not always set, sometimes preferring to rely on the order of IDs, or on `include`'s, e.g. `ocds-docs-live` doesn't require `pkg: git` for a `git.latest`
* [x] `ocdskingfisherscrape.sls` enables the proxy and proxy_http Apache modules itself, instead of including `apache-proxy.sls`

In general, Pillar is used inconsistently for the same types of variables.

**Comment by jpmckinney** [comment] 2019-11-02 17:10
Related to `require`, do the elasticsearch IDs in standard-search.sls need to run before the rest of the file? If not, it might be possible to have a common django.sls that toucan and standard-search include.

**Comment by jpmckinney** [comment] 2019-11-02 20:30
I deployed standard-search and it's still working, but I don't know if that's because elasticsearch had already been installed, or if the order just doesn't matter.

**Comment by odscjames** [comment] 2020-09-08 13:03
Will look at specific things now, but generally:

> if the order just doesn't matter.

Yes, it does, but the problem is that you only see problems due to errors here:
* When installing a new box 
* When making some changes to some services where later services rely on those changes
In the first case you can just rerun the salt command several times, and it works out fine, as if you are installing a new box for the first time you wouldn't have any live traffic. In the latter case, you can usually do the same but some live traffic may see a broken server in the middle.
Essentially, given how salt comes to be written over time on existing boxes, it's very easy to end up writing salt that will fail in one of those 2 circumstances. And because those 2 circumstances rarely arise (and there's an easy workaround to the 1st one) it's not often caught. There's really not a way to catch it when developing, apart from testing every salt change on a totally new box.
Or at least that I know, others may know more - interesting discussion point for later maybe.

**Comment by odscjames** [comment] 2020-09-08 13:31
> prometheus-client-apache is last in top.sls, except for ocds-docs-* and standard-search

You mean in salt/top.sls? Don't think that is important to fix? require, watch, and prereq will primarily set the ordering anyway, and that can work across different state files - if we do realise any ordering needs to be done, we should do it with that. I'd prefer to avoid fixing for neatness sake; people may start thinking the order is important or that this is the correct place to fix ordering issues.

**Comment by odscjames** [comment] 2020-09-08 13:46
> ocdskingfisherscrape.sls enables the proxy and proxy_http Apache modules itself, instead of including apache-proxy.sls

Done and Kingfisher Deploy done

**Comment by odscjames** [comment] 2020-09-08 14:06
> apache_module.enabled generally has watch_in: service: apache2, except in apache-proxy.sls and ocds-docs-common.sls.

Both done, and Kingfisher and Docs Staging deploys

**Comment by odscjames** [comment] 2020-09-08 14:14
> require is not always set, sometimes preferring to rely on the order of IDs, or on include's, e.g. ocds-docs-live doesn't require pkg: git for a git.latest

How far do you want us to go with this? 

As explored in https://github.com/open-contracting/deploy/issues/71#issuecomment-688851295 these errors do unfortunately come up a lot. There could be quite a lot to check here. It may even end up checking every part of our existing salt, and having to run fresh installs of servers repeatedly on dummy servers which could take a while. 

Also as in the comment, the value of fixing some of these isn't high, as the potential for causing a problem is essentially nothing (eg the only time I can see  "ocds-docs-live doesn't require pkg: git for a git.latest" causing a problem is during a totally fresh server install when you have no live traffic and it's fixed with a simple re-run)

**Comment by odscjames** [comment] 2020-09-08 14:32
![](https://github.trello.services/images/mini-trello-icon.png) [Deploy - issues around ordering of salt actions](https://trello.com/c/vK4xH2Z6/228-deploy-issues-around-ordering-of-salt-actions)

**Comment by jpmckinney** [comment] 2020-09-08 21:35
We can defer the `require` clean up to #74. Dogsbody is much more consistent at using `require`.

> You mean in salt/top.sls? Don't think that is important to fix? require, watch, and prereq will primarily set the ordering anyway, and that can work across different state files - if we do realise any ordering needs to be done, we should do it with that. I'd prefer to avoid fixing for neatness sake; people may start thinking the order is important or that this is the correct place to fix ordering issues.

In my experience, things being inconsistently ordered suggests that the order matters. Things being consistently ordered doesn't necessarily mean anything, since it could just be for consistency's sake – a common feature of code that was written with care. Inconsistent ordering also stands out when scanning a file visually, whereas consistent ordering makes it easy to see if these lines are missing from any target. So, I'd rather make the order consistent.

**Comment by odscjames** [comment] 2020-09-09 14:01
Reordered and tested with a docs staging deploy. Think this can be closed now then.

**Closed by odscjames** 2020-09-09 14:01 UTC
Labels: for: ODSC, framework
